services:
  redyi-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: redyi:dev
    container_name: redyi-dev
    stdin_open: true
    tty: true
    network_mode: host

    gpus: all

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.Xauthority
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia

    volumes:
      - ./ros2_ws/src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/tmp/.Xauthority:ro

    command: bash